name: Update Data
on:
  push:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update AzurLaneData
        run: git submodule update --init --recursive --remote
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Installing dependencies
        run: npm ci
      - name: Running translater
        run: npm start
      - name: Create commits
        run: |
          git config user.name 'Kumo'
          git config user.email 'octo-kumo@users.noreply.github.com'
          git commit -am "Auto Update"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: '[Auto] Data Test'
          branch: 'update'
          body: ''
          labels: data update, automated

